name: Push Docker Images to DockerHub

on:
  push:
    branches: [ "main" ]

jobs:
  push-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build backend image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/freelancer-backend:latest .

      - name: Push backend image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/freelancer-backend:latest

  push-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build frontend image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/freelancer-frontend:latest .

      - name: Push frontend image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/freelancer-frontend:latest
